---
# tasks file for nginx

 - name: install Docker Engine on Amazon Linux 
   shell: amazon-linux-extras install -y docker
   
 - name: Install docker-py
   pip:
     name: docker

 - name: start Docker
   systemd:
     name: docker
     state: started
     enabled: yes
     
 - name: generate nginx.conf
   template:
     src: nginx.conf.j2
     dest: /etc/nginx.conf
     owner: root
    
 - name: run Nginx container
   docker_container:
     name: balancer
     image: nginx
     recreate: yes
     ports:
       - 80:80
     volumes:
       - /etc/nginx.conf:/etc/nginx/nginx.conf
     networks:
       - name: network_app
